### PR TITLE
Create New Post

### LINKED ISSUE #41: create post edited
## Post 
- As a profile owner, when I can click ‘create new request’, I will be redirected to a page and asked to give other users more information about the post so they can have a complete information on what kind of help I’m asking.
The story is considered done where the following information is inserted for posting help.       

- [x] Title of your help (mandatory)    
- [x] Location (mandatory)    
- [x] Category (mandatory)
- [x] Description (mandatory)

### PR DESCRIPTION
**Pull request by yildiraykoyuncu**
- [x] new post form opens when the user clicks request help
- [x] it goes away if the user clicks cancel
- [x] after the user submits the post it appears on the newsfeed page

close #41

### CODE REVIEW

**Comment by dirk-jacobs** [comment]
Seems to do the job

**Review by adekimpianna — APPROVED** [review]

**Review by oguzkarademir — APPROVED** [review]
very nice @yildiraykoyuncu

**Review by gelilaa — APPROVED** [review]
🔥 🚀

**Comment by LujiAnna** [comment]
Works well on my end, with all its functionalities 💯

**Review by LujiAnna — APPROVED** [review]
Works super ..

**Pull request merged**
