### PR TITLE
add navbar components and styles

### PR DESCRIPTION
**Pull request by yildiraykoyuncu**
Added navbar signedIn signedOut components,
Installed node-sass and added App.scsss file to customize react-bootstrap components

### CODE REVIEW

**Comment by mametur** [comment]
@yildiraykoyuncu nice component. I think if you start design mobile first approach it will be nice. For mobile version when you click on hamburger button after that showing sign-in and sign-up buttons place where should be? Maybe you still work on it.

incase someone encounter this error when trying to check pull request [dependencies error](https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0)

**Review by mametur — COMMENTED** [review]
@yildiraykoyuncu nice component. I think if you start design mobile first approach it will be nice. For mobile version when you click on hamburger button after that showing sign-in and sign-up buttons. How will you show them? Maybe you still work on it.

incase someone encounter this error when trying to check pull request [dependencies error](https://stackoverflow.com/questions/64625050/error-node-sass-version-5-0-0-is-incompatible-with-4-0-0) it fixed for me

**Comment by yildiraykoyuncu** [comment]
Button sizes for small screens have been fixed

**Review by gelilaa — APPROVED** [review]
Looks great, 🚀 
one thing to bear in mind is that the buttons don't go col-12 when they are in mobile mode. but can be fixed later on.

**Review by mametur — APPROVED** [review]
Maybe later on we can think about for hamburger button, When you click on it then it shows black outline so maybe we can remove it later on.`=> button:focus {outline:none} .
`
@yildiraykoyuncu Good job ..Ready for merging  I think:)

**Comment by yildiraykoyuncu** [comment]
> Looks great, 🚀
> one thing to bear in mind is that the buttons don't go col-12 when they are in mobile mode. but can be fixed later on.

I fixed this one I think it goes col-12 in small screen now

**Comment by yildiraykoyuncu** [comment]
> Maybe later on we can think about for hamburger button, When you click on it then it shows black outline so maybe we can remove it later on.`=> button:focus {outline:none} . `
> @yildiraykoyuncu Good job ..Ready for merging I think:)

Yeap you are right the outline around it is annoying 😄. It was default with navbar component of bootstrap so just left it there may be later we can remove it completely or we can just remove the outline as you said. 👍

**Comment by oguzkarademir** [comment]
seems very good 👏 @yildiraykoyuncu

**Review by oguzkarademir — APPROVED** [review]

**Pull request merged**
