### PR TITLE
Reset-password Frontend/BackEnd

### LINKED ISSUE #26: userstory-Security - reset password
## Password
 As a user, I can recover my password if I&#39;ve forgotten it

  - The story is considered done when after clicking on &quot;Forgot password&quot;, I will be redirected to another page to enter my email address receive an email with my password.

- [x] verify path doesn't work

### PR DESCRIPTION
**Pull request by gelilaa**
- [x] user forgets its password

- [x] user asks to reset it and provides its email address

- [x]  user gets link with a token on their email
- [x]  user clicks the email link and resets its password
- [x]  user's new password get saved on the database with a hash
- [x]  user can sign in with a new password
- [x] Closes #26

### CODE REVIEW

**Comment by miroslavveljanoski** [comment]
I checked this branch on my local machine and when I'm trying to send my email on forgot password it doesn't work. I didn't receive an email to reset my password, only I'm getting this error in the console - Error: Unauthorized (401). It says that this error is from forgot.js file/line 13 - which means is failing in the __catch error__ part. 
>     Error: Unauthorized (401) at C:\Users\Miroslav\Documents\HYF\VoxBox\api\routes\forgot.js:131:17
After this Gelila send me an email to reset my password but that also didn't work, when I'm trying to reset my password I'm getting an alert with a message - undefined.

**Comment by gelilaa** [comment]
> 
> 
> I checked this branch on my local machine and when I'm trying to send my email on forgot password it doesn't work. I didn't receive an email to reset my password, only I'm getting this error in the console - Error: Unauthorized (401). It says that this error is from forgot.js file/line 13 - which means is failing in the **catch error** part.
> 
> > ```
> > Error: Unauthorized (401) at C:\Users\Miroslav\Documents\HYF\VoxBox\api\routes\forgot.js:131:17
> > ```
> 
> After this Gelila send me an email to reset my password but that also didn't work, when I'm trying to reset my password I'm getting an alert with a message - undefined.

the problem is the id i send you and the id you have on your machine are different...we will fix this today together

**Review by miroslavveljanoski — APPROVED** [review]
🚀

**Review by oguzkarademir — APPROVED** [review]
As I saw, Frontend side is not up to date. Functionality is working. Great job @gelilaa

**Review by mametur — APPROVED** [review]

**Pull request merged**
